### ISSUE TITLE
Navigation troubles

### ISSUE THREAD

**Issue by sbucholtz** [plexinc-plugins/TWiT.bundle#10]
My most common activity is going to the Recent Twit Shows feed.

When selecting that I see a list of shows, but the poster next to them is the All Twit Shows poster, rather than the poster for the individual show. Since the text field does not include the name of the show (Episode number and Episode Title) it becomes necessary to guess at the show by topic.

The proper poster for the show should be displayed or the series name included in the text.
![image1](https://cloud.githubusercontent.com/assets/10558016/9866604/0539fca0-5b19-11e5-910e-fecb7059bf0b.JPG)

**Comment by sander1** [comment]
This has been updated here https://github.com/plexinc-plugins/TWiT.bundle/commit/42b04c785ab69f7b8f05bd2a334217f432ec43d3
