### ISSUE TITLE
TWiT Live on Samsung Smarthub

### ISSUE THREAD

**Issue by VDRrulez** [plexinc-plugins/TWiT.bundle#9]
Please add 'Samsung' to HLS_COMPAT list. Tested on my Samsung UHD 2014 model. Works flawlessly. Thanks!

**Comment by sander1** [comment]
Done!

**Comment by VDRrulez** [comment]
Thanxalot! Works.

Am 25.05.2015 um 15:13 schrieb Sander Spies:
